array_layout = "Visual"
chain_indent = "Visual"
chain_one_line_max = 40
chain_split_single_child = true
closure_block_indent_threshold = -1
condense_wildcard_suffixes = true
fn_args_density = "Tall"
fn_args_layout = "Visual"
fn_call_style = "Visual"
fn_call_width = 50
fn_return_indent = "WithWhereClause"
fn_single_line = true
generics_indent = "Visual"
max_width = 70
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true